#include "main.hpp"

void CDisplayModule::Init(void)
{
	DigitClear();
	DigitSelect(DISPLAY_DIGIT_OFF);
	u32DigitCurrent = 0;
}

void CDisplayModule::Handle(void)
{
	DigitClear();
	u32DigitCurrent = (u32DigitCurrent + 1) % DISPLAY_DIGIT_COUNT;
	DigitSelect(u32DigitCurrent);
	DigitSet(u8Digit[u32DigitCurrent]);
}

void CDisplayModule::PrintDec(unsigned int u32Number)
{
	for(int s32Idx = 0; s32Idx < DISPLAY_DIGIT_COUNT; s32Idx++)
	{
		if(u32Number == 0 && s32Idx != 0)
		{
			u8Digit[s32Idx] = DISPLAY_DIGIT_OFF;
		}
		else
		{
			u8Digit[s32Idx] = u32Number % 10;
			u32Number /= 10;
		}
	}
}

void CDisplayModule::PrintBCD(unsigned int u32Number)
{
	for(int s32Idx = 0; s32Idx < DISPLAY_DIGIT_COUNT; s32Idx++)
	{
		u8Digit[s32Idx] = u32Number & 0xF;
		u32Number >>= 4;
	}
}

void CDisplayModule::DigitSelect(unsigned int u32DigitIdx)
{
	switch(u32DigitIdx)
	{
	case DISPLAY_DIGIT_OFF:
		LL_GPIO_SetOutputPin(PIN_DISPLAY_DIG_0_PORT, PIN_DISPLAY_DIG_0_PIN);
		LL_GPIO_SetOutputPin(PIN_DISPLAY_DIG_1_PORT, PIN_DISPLAY_DIG_1_PIN);
		LL_GPIO_SetOutputPin(PIN_DISPLAY_DIG_2_PORT, PIN_DISPLAY_DIG_2_PIN);
		break;
	case 0:
		LL_GPIO_SetOutputPin(PIN_DISPLAY_DIG_2_PORT, PIN_DISPLAY_DIG_2_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_DIG_0_PORT, PIN_DISPLAY_DIG_0_PIN);
		break;
	case 1:
		LL_GPIO_SetOutputPin(PIN_DISPLAY_DIG_0_PORT, PIN_DISPLAY_DIG_0_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_DIG_1_PORT, PIN_DISPLAY_DIG_1_PIN);
		break;
	case 2:
		LL_GPIO_SetOutputPin(PIN_DISPLAY_DIG_1_PORT, PIN_DISPLAY_DIG_1_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_DIG_2_PORT, PIN_DISPLAY_DIG_2_PIN);
		break;
	}
}

void CDisplayModule::DigitSet(unsigned char u8Digit)
{
	DigitClear();

	switch(u8Digit)
	{
	case DISPLAY_DIGIT_OFF:
		break;
	case 0:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_E_PORT, PIN_DISPLAY_SEG_E_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_F_PORT, PIN_DISPLAY_SEG_F_PIN);
		break;
	case 1:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		break;
	case 2:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_E_PORT, PIN_DISPLAY_SEG_E_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
		break;
	case 3:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
		break;
	case 4:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_F_PORT, PIN_DISPLAY_SEG_F_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
		break;
	case 5:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_F_PORT, PIN_DISPLAY_SEG_F_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
		break;
	case 6:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_E_PORT, PIN_DISPLAY_SEG_E_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_F_PORT, PIN_DISPLAY_SEG_F_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
		break;
	case 7:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		break;
	case 8:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_E_PORT, PIN_DISPLAY_SEG_E_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_F_PORT, PIN_DISPLAY_SEG_F_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
		break;
	case 9:
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_F_PORT, PIN_DISPLAY_SEG_F_PIN);
		LL_GPIO_ResetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
		break;
	}
}

void CDisplayModule::DigitClear(void)
{
	LL_GPIO_SetOutputPin(PIN_DISPLAY_SEG_A_PORT, PIN_DISPLAY_SEG_A_PIN);
	LL_GPIO_SetOutputPin(PIN_DISPLAY_SEG_B_PORT, PIN_DISPLAY_SEG_B_PIN);
	LL_GPIO_SetOutputPin(PIN_DISPLAY_SEG_C_PORT, PIN_DISPLAY_SEG_C_PIN);
	LL_GPIO_SetOutputPin(PIN_DISPLAY_SEG_D_PORT, PIN_DISPLAY_SEG_D_PIN);
	LL_GPIO_SetOutputPin(PIN_DISPLAY_SEG_E_PORT, PIN_DISPLAY_SEG_E_PIN);
	LL_GPIO_SetOutputPin(PIN_DISPLAY_SEG_F_PORT, PIN_DISPLAY_SEG_F_PIN);
	LL_GPIO_SetOutputPin(PIN_DISPLAY_SEG_G_PORT, PIN_DISPLAY_SEG_G_PIN);
}
